### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by brtsai** [brtsai/food-help#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use certain features without logging in (create reviews, ratings, business pages)

**Comment by ajansel** [comment]
This looks good to me! The only piece of advice I have is reducing the amount of white space on sign up when the errors render so that the form doesn't get pushed down as far. 

Also, I would consider the home page to be a part of search so it is adequate for now!

**Comment by mladenoff** [comment]
LGTM
