### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by brtsai** [brtsai/food-help#2]
Initial Deployment:

- [x] Initial push to heroku

Final Deployment

- [x] Remove console statements: debuggers, console.logs, errors, minification warnings, mixed content warnings
- [x] Use dev tools in dev environment

Bonus:

- [ ] Use custom domain name

**Comment by ajansel** [comment]
This looks good for now! We will close this officially assuming the final checkboxes are complete on Friday.

**Comment by mladenoff** [comment]
LGTM
