### ISSUE TITLE
PA Review: Production README

### ISSUE THREAD

**Issue by brtsai** [brtsai/food-help#7]
*Content*
- [x] Has a Production README in the project's github repository
- [x] Has a # Title
- [x] Links to the Wiki design documents
- [x] Describes technologies used
- [x] Describes core functionality
- [x] Lists future directions
- [x] Fills out Description and Website at the top of the repo.

*Format:*
- [x] Uses markdown formatting
- [x] Includes code snippets (with triple backticks, and the language ``)
- [x] Includes screenshots / gifs

*Optional*
- [x] Add topics to the top of the repo

**Comment by mladenoff** [comment]
This is pretty sparse.

- [x] Talk about the technologies you used and why ("why" as if you _would_ have made the choice to use them; pretend they were not assigned)
- [x] Talk about a particular feature that was interesting or challenging to write preferably with
- [x] Code examples
- [x] Have some screenshots

Take a look at this one: https://github.com/s-pangburn/small/blob/master/README.md

**Comment by mladenoff** [comment]
LGTM
